<a href="https://colab.research.google.com/github/kurt980/OA_practice/blob/main/McKinsey_practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [23]:
import pandas as pd
import numpy as np
import sklearn
import datetime

In [8]:
# initialize list of lists
data = [['tom', 10], ['tom',20], ['nick', 12], ['juli',5], ['juli', 14]]
  
# Create the pandas DataFrame
df = pd.DataFrame(data, columns=['Name', 'Age'])

In [28]:
df

Name  Age  Height       date
0   tom   10     1.5 2022-01-01
1   tom   20     1.6 2022-10-01
2  nick   12     1.9 2022-11-01
3  juli    5     1.7 2022-04-01
4  juli   14     1.7 2022-02-01

Fill NAs
https://www.geeksforgeeks.org/replace-nan-values-with-zeros-in-pandas-dataframe/

In [ ]:
#For one column using pandas:
df['DataFrame Column'] = df['DataFrame Column'].fillna(0)
#For one column using numpy:
df['DataFrame Column'] = df['DataFrame Column'].replace(np.nan, 0)
#For the whole DataFrame using pandas:
df.fillna(0)
#For the whole DataFrame using numpy:
df.replace(np.nan, 0)

Convert to float
https://sparkbyexamples.com/pandas/pandas-convert-string-to-float-type-dataframe/

In [3]:
# convert "Fee" from string to float
df['Age'] = df['Age'].astype(float)

Find name for highest average

In [ ]:
df = df.groupby(['Name'])[['Age']].mean().reset_index()

In [ ]:
df = df.sort_values(by = ['Age'], ascending = False).reset_index()

In [ ]:
df['Name'][0]

'tom'

Remove non-numeric characters

In [5]:
df['Name'] = df['Name'].str.extract('(\d+)', expand=False)

Highest correlation

In [10]:
df['Height'] = (1.5,1.6,1.9,1.7,1.7)

In [14]:
corr_matrix = abs(df.corr())

In [15]:
sol = (corr_matrix.where(np.triu(np.ones(corr_matrix.shape), k=1).astype(bool))
                  .stack()
                  .sort_values(ascending=False))

In [16]:
sol

Age  Height    0.116549
dtype: float64

In [20]:
np.triu(np.ones(corr_matrix.shape),k=1)

array([[0., 1.],
       [0., 0.]])

In [21]:
np.ones(corr_matrix.shape)

array([[1., 1.],
       [1., 1.]])

In [22]:
np.triu(corr_matrix, k = 1)

array([[0.        , 0.11654906],
       [0.        , 0.        ]])

Get difference in days

In [40]:
today = pd.to_datetime('today')

In [43]:
df['date'] = pd.to_datetime(['2022-01-01', '2022-10-01', '2022-11-01', '2022-04-01', '2022-02-01'])
df['days'] = (today - df['date']).dt.days

In [48]:
df[df['days'] > 1].shape[0]

4